
import javax.swing.*;
import java.io.*;
import java.net.*;

public class details extends javax.swing.JFrame {

    /** Creates new form details */
    public details() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        accno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        branch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cdob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cadd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        creditcardno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        issuedate = new javax.swing.JTextField();
        expirydate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cvv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        getdata = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Account Number");

        jLabel2.setText("Customer Name");

        cname.setEditable(false);

        jLabel3.setText("Branch");

        branch.setEditable(false);

        jLabel4.setText("Date of Birth");

        cdob.setEditable(false);
        cdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdobActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        cadd.setEditable(false);

        jLabel6.setText("Phone Number");

        jLabel7.setText("Credit Card number");

        creditcardno.setEditable(false);

        jLabel8.setText("Date of Issue");

        jLabel9.setText("Expiry Date");

        issuedate.setEditable(false);

        expirydate.setEditable(false);

        jLabel10.setText("Balance");

        balance.setEditable(false);

        jLabel11.setText("CVV no.");

        cvv.setEditable(false);

        jLabel12.setText("MID");

        mid.setEditable(false);

        getdata.setText("Get Details");
        getdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdataActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getdata)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cdob)
                        .addComponent(branch)
                        .addComponent(cname)
                        .addComponent(accno, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cadd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balance)
                            .addComponent(expirydate)
                            .addComponent(issuedate)
                            .addComponent(creditcardno, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mid))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logout)
                        .addGap(138, 138, 138))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(accno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditcardno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expirydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cadd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getdata)
                    .addComponent(logout))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdobActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cdobActionPerformed

private void getdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdataActionPerformed
    String flag;
    String dcname = null, dbranch = null, dcadd = null, dcreditcardno = null, dbalance = null, dcvc = null, dcdob = null, dexpirydate = null, dissuedate = null, response = null, dmid = null;
    String acc = accno.getText();
    String phone = phno.getText();
    int i, j, k, l, m, n, o, p, q, a;
    if (acc.equals("") || acc.length() != 13) {
        JOptionPane.showConfirmDialog(rootPane, "Please enter 13 digit Account Number", "Error", JOptionPane.OK_CANCEL_OPTION);
        return;
    } else if (phone.equals("") || phone.length() != 10) {
        JOptionPane.showConfirmDialog(rootPane, "Please enter Phone Number 10digit", "Error", JOptionPane.OK_CANCEL_OPTION);
        return;
    } else if (acc.equals("") && phone.equals("")) {
        JOptionPane.showConfirmDialog(rootPane, "Please enter 13 digit Account Number\nEnter Phone Number", "Error", JOptionPane.OK_CANCEL_OPTION);
        return;
    }
    try {
        Socket clientSocket = new Socket("59.181.113.78", 24000);
        DataOutputStream outToServer = new DataOutputStream(clientSocket.getOutputStream());
        String s = new String(acc + "p" + phone + "\n");
        System.out.println(s);
        outToServer.writeUTF(s);
        System.out.println("coming after sending");
        BufferedReader inFromServer = new BufferedReader(new InputStreamReader(clientSocket.getInputStream()));
        response = inFromServer.readLine();
        System.out.println(response);

        a = response.lastIndexOf(')');
        i = response.lastIndexOf('!');
        j = response.lastIndexOf('@');
        k = response.lastIndexOf('#');
        l = response.lastIndexOf('$');
        m = response.lastIndexOf('%');
        n = response.lastIndexOf('^');
        o = response.lastIndexOf('&');
        p = response.lastIndexOf('*');
        q = response.lastIndexOf('(');
        flag = response.substring(a - 1, a);
        System.out.println("flag" + flag);

        if (flag.equals("0")) {
            JOptionPane.showConfirmDialog(rootPane, "Record Doesn't Exist!\nPlease check the account number and phone number", "Error", JOptionPane.OK_CANCEL_OPTION);
            return;

        }
        dcname = response.substring(a + 1, i);
        cname.setText(dcname);

        dbranch = response.substring(i + 1, j);
        branch.setText(dbranch);

        dcdob = response.substring(j + 1, k);
        cdob.setText(dcdob);

        dcadd = response.substring(k + 1, l);
        cadd.setText(dcadd);

        dcreditcardno = response.substring(l + 1, m);
        creditcardno.setText(dcreditcardno);
        dexpirydate = response.substring(m + 1, n);
        expirydate.setText(dexpirydate);
        dissuedate = response.substring(n + 1, o);
        issuedate.setText(dissuedate);
        dcvc = response.substring(o + 1, p);
        cvv.setText(dcvc);
        dbalance = response.substring(p + 1, q);
        balance.setText(dbalance);
        dmid = response.substring(q + 1, response.length());
        mid.setText(dmid);


        clientSocket.close();

    } catch (Exception ex) {
    }
}//GEN-LAST:event_getdataActionPerformed

private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    adminlogin ad = new adminlogin();
    ad.setTitle("Admin Login");
    ad.setSize(400, 400);
    this.setVisible(false);
    ad.setVisible(true);
}//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accno;
    private javax.swing.JTextField balance;
    private javax.swing.JTextField branch;
    private javax.swing.JTextField cadd;
    private javax.swing.JTextField cdob;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField creditcardno;
    private javax.swing.JTextField cvv;
    private javax.swing.JTextField expirydate;
    private javax.swing.JButton getdata;
    private javax.swing.JTextField issuedate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logout;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField phno;
    // End of variables declaration//GEN-END:variables
}
